### ISSUE TITLE
Convert .tbx tools to .pyt: Distance and Direction

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-geoprocessing-toolbox#273] opened 2018-05-02 07:20 UTC
### Task to be done - May 16th 2018
- [x] Modify checklist test to add input feature sets

--------------------------------------------------------
Issue https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/262 has been broken down into toolsets. The Distance and direction tools are:

- [X] RangeRingsFromInterval - #268
- [X] RangeRingFromMinimumAndMaximum - #268
- [X] RangeRingsFromMinAndMaxTable - #268

Acceptance Criteria:
Target release: Military Tools 3.0
Pro 2.1 and 2.2
10.3.1+
One toolbox
Team works together to understand the tests that are currently running.
Tests written and running for tools: Team works together to design additional tests (result expectation).
Toolset included in the toolbox in the .zip
Tools documented
Tools tested
User documentation complete and published

**Comment by ACueva** [comment] 2018-05-04 22:45
Jenkins Unit tests now run.
Staging location for tests:
http://dev0002292:8080/job/GP%20Unit%20tests/

Tests are currently running against the master branch.  I have also run these tests against the dev branches of the https://github.com/Esri/military-tools-geoprocessing-toolbox repo.
Both these branches fail:

Broken Unit tests ArcMap:
**Master branch**
http://dev0002292:8080/job/GP%20Unit%20tests/job/ArcMap%20Test%20Runner/7/console
**Dev Branch**
http://dev0002292:8080/job/GP%20Unit%20tests/job/ArcMap%20Test%20Runner/5/console

Broken Unit tests ArcGIS Pro:
**Master branch**
http://dev0002292:8080/job/GP%20Unit%20tests/job/ArcGIS%20Pro%20Test%20Runner/2/console
**Dev Branch**
http://dev0002292:8080/job/GP%20Unit%20tests/job/ArcGIS%20Pro%20Test%20Runner/1/console

FYI @csmoore

**Comment by BobBooth** [comment] 2018-05-07 17:35
Tool help migrated to the PYT tools in this PR:
https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/281

**Comment by BobBooth** [comment] 2018-05-07 18:56
Updated What's New an Military Tools home page in GitHub to indicate conversion to PYT format, in PR https://github.com/ArcGIS/arcgis-solutions-website/pull/6431

**Comment by ACueva** [comment] 2018-05-07 21:31
Verified TestRunner.py imports and runs Distance and Direction test suite:
http://dev0002292:8080/job/GP%20Unit%20tests/job/ArcMap%20Test%20Runner/14/console

**Comment by csmoore** [comment] 2018-05-09 14:33
@ACueva - I'm not able to reproduce the [unit test error above](https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/273#issuecomment-387100540) with my Pro 2.1 and the latest test suite - we may need to debug on that machine if the problem persists.

```
INFO: 2018-05-09 09:28:50,823 ------------ Begin Tests ------------------
INFO: 2018-05-09 09:28:50,837 Platform: Windows-10-10.0.16299-SP0
INFO: 2018-05-09 09:28:50,837 Python Version 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
INFO: 2018-05-09 09:28:50,840 Product: ArcGISPro, Version: 2.1, Installed on: 1/8/2018, Build: 10257.
INFO: 2018-05-09 09:28:50,840 -------------------------------------------

...


INFO: 2018-05-09 09:46:42,438 Test success: True
INFO: 2018-05-09 09:46:42,439
RESULTS =================================================
Number of tests run: 86
Number succeeded: 86
Number of errors: 0
Number of failures: 0
Number of tests skipped: 0
Percent passing: 100.0
=========================================================
```

**Comment by ACueva** [comment] 2018-05-10 21:36
Issue with Pro 2.1 toolbox failing was a result of the branch being used.  Changed all unit tests to run against the Dev branch of the Esri/MTGPToolbox repo.

```
INFO: 2018-05-10 14:02:34,560 
RESULTS =================================================
Number of tests run: 86
Number succeeded: 86
Number of errors: 0
Number of failures: 0
Number of tests skipped: 0
Percent passing: 100.0
=========================================================

INFO: 2018-05-10 14:02:34,561 END OF TEST =========================================
```

**Comment by ACueva** [comment] 2018-05-10 22:01
Ran through Checklist test, no functional changes were needed: https://github.com/ArcGIS/solutions-defense-test-catalog/blob/master/Tests/Gridded-Reference-Graphic_ArcMap-ArcGIS-Pro.md

**Comment by ACueva** [comment] 2018-05-11 23:36
GP checklist created.  Ready for review. https://github.com/ArcGIS/solutions-defense-test-catalog/pull/133
FYI @BobBooth @dfoll @topowright

**Comment by dfoll** [comment] 2018-05-14 22:30
Removing G - QC Checklist (Verify) .... verified the checklist exists, and verified that the tools pass the steps in the checklist. No other labels remain, so I am moving this to done

**Comment by ACueva** [comment] 2018-05-15 16:27
Changes made to Checklist test per https://github.com/ArcGIS/solutions-defense-test-catalog/pull/133

**Comment by csmoore** [comment] 2018-05-15 21:50
The FeatureSet inputs are definitely broken for these 3 tools in the pyt: the problem is with the [input schema layer](https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/dev/toolboxes/scripts/DistanceAndDirectionTools.py#L58): toolboxes\layers\RangeRingInputObserversGDB.lyr - this layer needs to be recreated. @BobBooth and I learned as part of this process that only the Save-To-Layer GP tool creates the layer with the necessary relative paths to make the lyr file portable (lyrs that point to a live GDB is a new requirement of the pyt)

**Closed** 2018-05-22 22:39 UTC
Labels: A-feature, E-verified
