### ISSUE TITLE
Linear Line of Sight in Visibility toolset is attaching multiple profile graphs to the first row in the table

### ISSUE THREAD

**Issue by dfoll** [Esri/military-tools-geoprocessing-toolbox#185] opened 2016-12-08 22:30 UTC
## Expected Behavior
each row in the output los table should have just one profile graph attached to it

## Current Behavior
the first row in the table is getting multiple graphs attached to it. what it looks like it is doing is it is attaching the profile graph for row one, and attaching the graph for all other rows that start with a "1"...for example, row1 is also picking up the attachments for row10, row11, row12, row13, row14, row15, row16, so i would guess this happens again in the event that a user has 20 or more output lines of sight, row2 would start picking up multiple attachments. side note, later in the list, the correct lines are still getting their appropriate attachment... for example the attachment for row14 is attached to row1, and row 14

## Steps to Reproduce (for bugs)

1. run linear line of sight with the TestData from the repo using LLOS_Observers and LLOS_Targets

## Your Environment

* Version used: 10.3.1

**Comment by mfunk** [comment] 2017-03-17 14:23
Tested on ArcMap 10.5

Testing data from MTGT repo:
* .\military-tools-geoprocessing-toolbox\testdata\MilitaryToolsTestData.gdb\LLOS_Observers
* .\military-tools-geoprocessing-toolbox\testdata\MilitaryToolsTestData.gdb\LLOS_Targets
* .\military-tools-geoprocessing-toolbox\testdata\Elevation\Source\SRTM30M\n36.dt2

1) Open ArcMap
1) Add testing data listed above
1) Open Linear Line Of Sight tool from *Military_Tools_arcmap.tbx\Visibility*
1) Set parameters:
Observers: LLOS_Observers
Obsever Height Above Surface: 2 (default)
Targets: LLOS_Targets
Target Height Above Surface: 0 (default)
Input Elevation Surface: n36.dt2 
1) Select **OK**

```
Executing: LinearLineOfSight LLOS_Observers 2 LLOS_Targets 0 n36.dt2 D:\Workspace\Test\Test_MTGT_Issue_185\scratch.gdb/outputLOS D:\Workspace\Test\Test_MTGT_Issue_185\scratch.gdb/outputSightLines D:\Workspace\Test\Test_MTGT_Issue_185\scratch.gdb/outputObservers D:\Workspace\Test\Test_MTGT_Issue_185\scratch.gdb/outputTargets #
Start Time: Fri Mar 17 07:19:23 2017
Running script LinearLineOfSight...
OFFSET field not in Observers. Using Observer Height Above Surface value of 2
OFFSET field not in Targets. Using Target Height Above Surface value of 0
Projecting Observers and Targets to Input Surface spatial reference GCS_WGS_1984
Adding field OFFSET with alias Offset above surface
Adding field OFFSET with alias Offset above surface
Building 3D observer points...
Adding surface info for prjObservers
Adding field ObsSPOT with alias ObsSPOT
Building 3D target points...
Adding surface info for prjTargets
Adding field TgtSPOT with alias TgtSPOT
Constructing Sight Lines between observers and targets...
Building minimum bounding rectangle of sight lines for analysis mask...
Building Line Of Sight...
Joining attribute results...
Attributing output Observer features...
Calculating frequency on Target features...
Building profile graph...
Found 16 unique sight line IDs ...
Building graphs for lines ...
Building graph from observer 1 to target 1 ...
Building graph from observer 1 to target 2 ...
Building graph from observer 1 to target 3 ...
Building graph from observer 1 to target 4 ...
Building graph from observer 2 to target 1 ...
Building graph from observer 2 to target 2 ...
Building graph from observer 2 to target 3 ...
Building graph from observer 2 to target 4 ...
Building graph from observer 3 to target 1 ...
Building graph from observer 3 to target 2 ...
Building graph from observer 3 to target 3 ...
Building graph from observer 3 to target 4 ...
Building graph from observer 4 to target 1 ...
Building graph from observer 4 to target 2 ...
Building graph from observer 4 to target 3 ...
Building graph from observer 4 to target 4 ...
Enabling attachments ...
Building match table ...
Attaching profile graphs to sightlines ...
Completed script LinearLineOfSight...
Succeeded at Fri Mar 17 07:20:24 2017 (Elapsed Time: 1 minutes 0 seconds)
```
Checking results...
![image](https://cloud.githubusercontent.com/assets/3093182/24047232/5072fb98-0ae2-11e7-88ce-d6bc6fb39d82.png)

Looking at the surface line output, line OID=1 has 8 attachments, where it should only have 1:
![image](https://cloud.githubusercontent.com/assets/3093182/24047293/7c03613a-0ae2-11e7-8715-9a8400af2db8.png)

It should have profile1.png, but it also includes 10, 11, 12,13,14,15,16.

**Comment by mfunk** [comment] 2017-03-17 14:31
Looking at code in *LLOSProfileGraphAttachments.py* the stuff that matches the surface lines with their profile graph is around lines 171 to 181:

```
    arcpy.AddMessage("Enabling attachments ...")
    arcpy.EnableAttachments_management(inputFeatures)
    
    matchTable = os.path.join(scratchGDB,"matchTable")
    deleteme.append(matchTable)
    arcpy.AddMessage("Building match table ...")
    arcpy.GenerateAttachmentMatchTable_management(inputFeatures,scratchFolder,matchTable,"pngname","*.png","ABSOLUTE")
    
    arcpy.AddMessage("Attaching profile graphs to sightlines ...")
    inOIDField = arcpy.Describe(inputFeatures).OIDFieldName
    arcpy.AddAttachments_management(inputFeatures,inOIDField,matchTable,"MatchID","Filename")
```

So we are using the **GenerateAttachmentMatchTable** tool to build the matching table. If I look at the intermediate dataset we can see the problem:

![image](https://cloud.githubusercontent.com/assets/3093182/24047586/66aced82-0ae3-11e7-96c0-9cb1756cc9d5.png)

I'm going to look at the Generate Attachement Match Table tool...

**Comment by mfunk** [comment] 2017-03-31 21:29
Tried contacting the 'attachments' PE on this one but haven't heard back from them in two weeks.

**Comment by mfunk** [comment] 2017-04-05 15:43
From attachments PE:

*Sorry, I started looking into this and then forgot to respond. Thanks for reminding me!
This issue came in from support awhile back too, so I had to look up what we had decided at that time. It was decided that this is by design, and the key used to match must be unique. My guess is that what you’re seeing may have something to do with the behavior that allows multiple files with various extensions to match to a single record  Give it a try with the full name (‘profile1.png’) and let me know if you still see issues.*

Going to try to rewrite so that the profile field name is exactly the same as the profile graph file.

**Comment by mfunk** [comment] 2017-04-05 16:32
@dfoll Need to verify this one when #212  is merged.

**Comment by lfunkhouser** [comment] 2017-05-02 21:40
@dfoll is out. Adding the other PEs to pick it up. @topowright @ACueva @NatalieCampos

**Comment by topowright** [comment] 2017-05-03 21:55
This has been verified.

**Comment by lfunkhouser** [comment] 2017-05-09 20:15
Closing issue - @topowright verified as fixed.

**Closed by lfunkhouser** 2017-05-09 20:15 UTC
Labels: 4 - Done, B - Bug, effort-medium, F - Visibility, priority - normal, V - 10.3.1, V - 10.4.1, V - 10.5, V - Pro 1.2, V - Pro 1.3, V - Pro 1.4
