### ISSUE TITLE
Linear Line of Sight symbology incorrect in ArcGIS Pro

### ISSUE THREAD

**Issue by dfoll** [Esri/military-tools-geoprocessing-toolbox#387] opened 2018-11-08 20:34 UTC
Linear Line of Sight has an output layer for Sight Lines which is a binary visible/non-visible - white/black output, in ArcGIS Pro they are backwards, when there is a sight line between observer and target they are being colored black and when there is no direct sight line, they are being colored white.

Output target features are symbolized red or green for non-visible or visible and labeled with how many observers can see them.

## Expected Behavior
![image](https://user-images.githubusercontent.com/5322669/48271145-ab06fa80-e409-11e8-9845-24169f22677a.png)
Sight lines to visible targets are white, sight lines to non-visible targets are black.  Targets are colored green and  labeled with number of observers that can see them or red if they are non-visible.
_This screenshot is taken from ArcMap to show correct symbology_

## Current Behavior
![image](https://user-images.githubusercontent.com/5322669/48271338-19e45380-e40a-11e8-8cad-825e2f6891ab.png)
Sight lines are reversed, the visible ones are black. Targets are all red, instead of being shown as green for ones that are visible (it is currently known that in ArcGIS Pro we are having trouble with the labels).

## Steps to Reproduce (for bugs)

1. Run Linear Line of Sight GP tool from the MT build 126 GP toolbox
2. `Observers`: LLOS_Observers
3. `Targets`: LLOS_Targets
4. `Input Elevation Surface`: ElevationUTM_Zone10
5. Keep all other defaults
Test data can be found in [MilitaryToolsTestData.gdb](https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/dev/utils/testdata)

## Your Environment
Was able to reproduce with ArcGIS Pro 2.2 with September release and build 126, and ArcGIS Pro 2.3 with build 126

**Comment by BobBooth** [comment] 2019-01-14 17:04
This is what I'm currently seeing, using the GP tool in the Military Tools.pyt
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/129126dc-904a-4e34-a35b-1971551758a8)
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/d05ce098-b072-4e1d-8ee5-310117c16d5d)

**Comment by BobBooth** [comment] 2019-01-16 17:54
It looks as though the problem is that particular point is visible from three of the four observer locations, but it is not visible from the last of the four, and that feature is the one being drawn on top, so it shows as red.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/233e6313-9c75-4f2b-9239-79e091dd09b0)
Perhaps for Pro we need the OutputTargets layer to be symbolized using the Frequency attribute.  The values are either NULL (for not visible from anywhere) or a number representing the number of observers who can see the location.
We could symbolize this with a Unique Values renderer on the Frequency field, where the value Null gets a red symbol, and all other values get a green symbol.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/3b27153f-10b3-4968-a38c-203f3bfa0ec2)

**Comment by csmoore** [comment] 2019-01-16 22:15
It looks to me like Pro and ArcMap are interpreting the symbol layer drawing order differently (the tool using the same .lyr file for both), just switching the symbol layer orders in Pro seems to resolve the issue.

To resolve we will probably have to have a different lyrx file for Pro (versus reusing the ArcMap one like we have been doing).

**Comment by csmoore** [comment] 2019-01-17 14:19
While testing the target symbology on **2.2** (sightline issue doesn't show up on 2.3), I also see [original issue](https://user-images.githubusercontent.com/5322669/48271338-19e45380-e40a-11e8-8cad-825e2f6891ab.png) with the reversed sightlines.  Looks like this was also a Pro bug with how it interpreted the ArcMap .lyr file, but this can also be fixed/worked-around by using the Pro lyrx file from the repo.

These output symbology bugs are likely left over from when we combined the Pro and ArcMap toolboxes.

**Comment by csmoore** [comment] 2019-01-17 21:47
Latest dev seems to look fine for me on 2.3 so not quite sure what the issue might be:

![image](https://user-images.githubusercontent.com/3090809/51350981-93866680-1a77-11e9-8f74-96f0e0706e6d.png)

**Comment by csmoore** [comment] 2019-01-18 14:33
Running on Pro 2.1, I saw the same problem @BobBooth did ( https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/387#issuecomment-455248728 ), so for me this problem seems to be isolated to, and be a bug with, Pro 2.1. If you run "Apply Symbology From Layer" GP Tool with the same layer files they seem to show up correctly.

**Comment by BobBooth** [comment] 2019-01-18 16:21
Using today's build on Pro 2.3, I am seeing the toolbox (PYT) LLOS tool and the LLOS tool from the Analysis toolbar both producing correctly symbolized and layer-described output.  I think this is a Pro 2.1 issue.

**Comment by BobBooth** [comment] 2019-01-18 18:40
Testing on Pro 2.1 and 2.2 with today's build I'm seeing correct symbology, but only the numeric value descriptions.  In Pro 2.3 the layer descriptions are the correct "Visible" "Not Visible" verbose descriptions.
As @csmoore mentioned, after running "Apply Symbology From Layer" GP Tool with the same layer files they show up correctly.
I created four new LYRX files using Pro 2.2 and tested on Pro 2.2, the symbology was again correct, but the descriptions were still simply numeric.  I suspect that this is a core issue with Pro 2.1 and Pro 2.1, which is fixed in Pro 2.3.

**Comment by BobBooth** [comment] 2019-01-18 20:47
To Do: Log a known issue in the Release notes that on Pro 2.1 (and maybe 2.2?) the layer category descriptions are numeric (0, 1) rather than verbose (Visible, Not Visible).

**Comment by BobBooth** [comment] 2019-01-22 16:17
Added to Release notes for MT, republished from CMS, rebuilt Jenkins.

**Closed** 2019-01-25 19:36 UTC
Labels: A-bug, E-verified, V -  Pro 2.1, V - MT 3.3
