### ISSUE TITLE
Distance and Direction Tools use in memory features in Pro 

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#184] opened 2016-12-08 19:00 UTC
Range rings from interval uses in memory features in Pro but Pro doesn't use in memory features.  This is confusing to the user who may not know the functionality doesn't exist.   An previous created point feature class with points in necessary to run the tools.  

![image](https://cloud.githubusercontent.com/assets/5116835/21023379/1fa2b92c-bd35-11e6-9573-989ea528f06c.png)

## Expected Behavior
I would expect that the in memory feature be removed so as to reduce the confusion of the user. 

## Current Behavior
Currently in memory feature is an option.  Pro will even run the tool with empty range rings feature class as output.  

## Possible Solution
remove in memory features as default.  

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by mfunk** [comment] 2016-12-08 19:23
Duplicate of #20

**Closed by mfunk** 2016-12-08 19:23 UTC
Labels: B - As Designed, B - Duplicate, F - Distance and Direction, V - Pro 1.3
