### ISSUE TITLE
Unable to run Radial Line of Sight and Range multiple times 

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#238] opened 2017-06-29 21:59 UTC
When running the Radial Line of Sight and Range gptool multiple times in 104.1 I get the following error.  I believe the error has something to do with the tools outputs being created as "in memory".  Worked with @dfoll to reproduce on his machine but was unable to.  See Error below.

`Executing: RadialLineOfSightAndRange "Feature Set" CA_CC_DTM_Meters_UTM.tif 3000 40 120 20 1000 in_memory\viewshed2 in_memory\wedge2 in_memory\fullwedge2
Start Time: Thu Jun 29 13:54:11 2017
Running script RadialLineOfSightAndRange...
Failed script RadialLineOfSightAndRange...

Traceback (most recent call last):
  File "C:\git\military-tools-geoprocessing-toolbox\toolboxes\scripts\RadialLineOfSightAndRange.py", line 328, in <module>
    main()
  File "C:\git\military-tools-geoprocessing-toolbox\toolboxes\scripts\RadialLineOfSightAndRange.py", line 323, in main
    innerRadiusInput, viewshed, sectorWedge, fullWedge)
  File "C:\git\military-tools-geoprocessing-toolbox\toolboxes\scripts\RadialLineOfSightAndRange.py", line 236, in createViewshed
    copyFeaturesAndProject(inputObserverPoints, tempObserverPoints, elevationSR)
  File "C:\git\military-tools-geoprocessing-toolbox\toolboxes\scripts\RadialLineOfSightAndRange.py", line 158, in copyFeaturesAndProject
    spatial_reference=spatial_reference)
  File "c:\program files (x86)\arcgis\desktop10.4\arcpy\arcpy\management.py", line 1806, in CreateFeatureclass
    raise e
ExecuteError: ERROR 000258: Output in_memory\tempPoints already exists
Failed to execute (CreateFeatureclass).

Failed to execute (RadialLineOfSightAndRange).
Failed at Thu Jun 29 13:54:11 2017 (Elapsed Time: 0.07 seconds)
`

**Comment by lfunkhouser** [comment] 2017-12-27 21:50
Closing. This functions As Designed. @dfoll was unable to reproduce and @csmoore offered the solution to set the GP Environment to "Overwrite Outputs"

**Closed by lfunkhouser** 2017-12-27 21:50 UTC
Labels: A-bug, E-as designed, T-visibility, V - 10.4.1
